apiVersion: v2
name: drone-rx
description: Medicine delivery by drone
type: application
version: 1.0.0 # x-release-please-version
appVersion: "1.0.0" # x-release-please-version

dependencies:
  - name: cloudnative-pg
    version: "0.28.0"
    repository: "https://cloudnative-pg.github.io/charts"
    condition: postgresql.enabled
  - name: nats
    version: "2.12.6"
    repository: "https://nats-io.github.io/k8s/helm/charts"
    condition: nats.enabled
  - name: replicated
    repository: oci://registry.replicated.com/library
    version: "1.19.1"
