{{- if and .Values.ingress.enabled .Values.ingress.tls.cloudflare.enabled .Values.ingress.tls.cloudflare.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.cloudflare.apiTokenSecretName }}
  labels:
    {{- include "dronerx.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  api-token: {{ .Values.ingress.tls.cloudflare.apiToken | quote }}
{{- end }}
