{{- if and (eq .Values.postgresql.enabled true) .Values.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dronerx.fullname" . }}-db-app
  labels:
    {{- include "dronerx.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/basic-auth
stringData:
  username: dronerx
  password: {{ .Values.postgresql.password | quote }}
{{- end }}
