apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dronerx.fullname" . }}-frontend
  labels:
    {{- include "dronerx.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "dronerx.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dronerx.frontend.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- include "dronerx.imagePullSecrets" . | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.frontend.port | quote }}
            - name: API_URL
              value: "http://{{ include "dronerx.fullname" . }}-api:{{ .Values.service.apiPort }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
