apiVersion: v1
kind: Service
metadata:
  name: {{ include "dronerx.fullname" . }}-frontend
  labels:
    {{- include "dronerx.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dronerx.frontend.selectorLabels" . | nindent 4 }}
