{{- if eq .Values.postgresql.enabled true }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "dronerx.fullname" . }}-db
  labels:
    {{- include "dronerx.labels" . | nindent 4 }}
  {{- if .Values.cnpgOperator.managed }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  imageName: {{ .Values.postgresql.imageName }}
  instances: {{ .Values.postgresql.instances }}
  imagePullSecrets:
    {{- include "dronerx.imagePullSecrets" . | nindent 4 }}
  bootstrap:
    initdb:
      database: dronerx
      owner: dronerx
  storage:
    size: {{ .Values.postgresql.storage.size }}
{{- end }}
