apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dronerx.fullname" . }}-preflight
  labels:
    {{- include "dronerx.labels" . | nindent 4 }}
    troubleshoot.sh/kind: preflight
stringData:
  preflight-spec: |
    {{ include "dronerx.preflight" . | nindent 4 }}
