apiVersion: v1
kind: Secret
metadata:
  name: drone-rx-cloudflare-api-token
  labels:
    app.kubernetes.io/name: drone-rx
    app.kubernetes.io/managed-by: kots
  annotations:
    kots.io/when: 'repl{{ and (ConfigOptionEquals "ingress_enabled" "1") (ConfigOptionEquals "tls_mode" "cloudflare") }}'
type: Opaque
stringData:
  api-token: 'repl{{ ConfigOption "cloudflare_api_token" }}'
