apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: drone-rx
spec:
  chart:
    name: drone-rx
    chartVersion: 0.0.0-dev.1776307712
  weight: 10
  builder:
    api:
      image:
        registry: ghcr.io
        repository: jmboby/dronerx-api
        tag: latest
    frontend:
      image:
        registry: ghcr.io
        repository: jmboby/dronerx-frontend
        tag: latest
    postgresql:
      enabled: true
      imageName: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie
    nats:
      enabled: true
      container:
        image:
          registry: index.docker.io
          repository: library/nats
      reloader:
        image:
          registry: index.docker.io
          repository: natsio/nats-server-config-reloader
      natsBox:
        container:
          image:
            registry: index.docker.io
            repository: natsio/nats-box
    busybox:
      image: index.docker.io/library/busybox:1.36
    replicated:
      image:
        registry: proxy.replicated.com
        repository: library/replicated-sdk-image
  values:
    cnpgOperator:
      managed: false
    busybox:
      image: repl{{ HasLocalRegistry | ternary (print LocalRegistryHost "/" LocalRegistryNamespace "/busybox:1.36") "images.littleroom.co.nz/anonymous/index.docker.io/library/busybox:1.36" }}
    api:
      image:
        registry: 'repl{{ HasLocalRegistry | ternary LocalRegistryHost "images.littleroom.co.nz" }}'
        repository: 'repl{{ HasLocalRegistry | ternary (print LocalRegistryNamespace "/dronerx-api") "proxy/drone-rx/ghcr.io/jmboby/dronerx-api" }}'
        tag: latest
      liveTrackingEnabled: 'repl{{ LicenseFieldValue "live_tracking_enabled" }}'
    frontend:
      image:
        registry: 'repl{{ HasLocalRegistry | ternary LocalRegistryHost "images.littleroom.co.nz" }}'
        repository: 'repl{{ HasLocalRegistry | ternary (print LocalRegistryNamespace "/dronerx-frontend") "proxy/drone-rx/ghcr.io/jmboby/dronerx-frontend" }}'
        tag: latest
    ingress:
      enabled: false
      tls:
        mode: "self-signed"
    postgresql:
      enabled: repl{{ ConfigOptionEquals "database_type" "embedded" }}
      imageName: repl{{ HasLocalRegistry | ternary (print LocalRegistryHost "/" LocalRegistryNamespace "/postgresql:18.3-system-trixie") "images.littleroom.co.nz/anonymous/ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie" }}
      instances: repl{{ ConfigOption "postgres_instances" | ParseInt }}
    externalDatabase:
      host: repl{{ ConfigOption "external_db_host" }}
      port: repl{{ ConfigOption "external_db_port" | ParseInt }}
      name: repl{{ ConfigOption "external_db_name" }}
      user: repl{{ ConfigOption "external_db_user" }}
      password: repl{{ ConfigOption "external_db_password" }}
      sslmode: repl{{ ConfigOption "external_db_sslmode" }}
    replicated:
      image:
        registry: 'repl{{ HasLocalRegistry | ternary LocalRegistryHost "images.littleroom.co.nz" }}'
    nats:
      container:
        image:
          registry: 'repl{{ HasLocalRegistry | ternary LocalRegistryHost "images.littleroom.co.nz/anonymous/index.docker.io" }}'
          repository: 'repl{{ HasLocalRegistry | ternary (print LocalRegistryNamespace "/nats") "library/nats" }}'
      reloader:
        image:
          registry: 'repl{{ HasLocalRegistry | ternary LocalRegistryHost "images.littleroom.co.nz/anonymous/index.docker.io" }}'
          repository: 'repl{{ HasLocalRegistry | ternary (print LocalRegistryNamespace "/nats-server-config-reloader") "natsio/nats-server-config-reloader" }}'
      natsBox:
        container:
          image:
            registry: 'repl{{ HasLocalRegistry | ternary LocalRegistryHost "images.littleroom.co.nz/anonymous/index.docker.io" }}'
            repository: 'repl{{ HasLocalRegistry | ternary (print LocalRegistryNamespace "/nats-box") "natsio/nats-box" }}'
      global:
        image:
          pullSecretNames:
            - enterprise-pull-secret
