apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: drone-rx
spec:
  chart:
    name: drone-rx
    chartVersion: $VERSION
  values:
    api:
      image:
        repository: images.littleroom.co.nz/proxy/drone-rx/ghcr.io/jmboby/dronerx-api
        tag: $VERSION
      liveTrackingEnabled: repl{{ LicenseFieldValue "live_tracking_enabled" }}
    frontend:
      image:
        repository: images.littleroom.co.nz/proxy/drone-rx/ghcr.io/jmboby/dronerx-frontend
        tag: $VERSION
    ingress:
      enabled: false
    postgresql:
      enabled: true
    cloudnative-pg:
      imagePullSecrets:
        - name: enterprise-pull-secret
    nats:
      global:
        image:
          pullSecretNames:
            - enterprise-pull-secret
