apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: drone-rx
spec:
  version: "3.0.0-alpha-31+k8s-1.34"
  extensions:
    helmCharts:
      - chart:
          name: cert-manager
          chartVersion: "v1.17.1"
        releaseName: cert-manager
        namespace: cert-manager
        values: |
          crds:
            enabled: true
          image:
            digest: ""
          webhook:
            image:
              digest: ""
          cainjector:
            image:
              digest: ""
          startupapicheck:
            image:
              digest: ""
