apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: traefik
spec:
  chart:
    name: traefik
    chartVersion: 39.0.7
  weight: 3
  helmUpgradeFlags:
    - --wait
    - --timeout=5m
  builder:
    image:
      registry: docker.io
      repository: traefik
      tag: v3.6.12
  values:
    image:
      registry: 'repl{{ ReplicatedImageRegistry (HelmValue ".Values.image.registry") }}'
      repository: 'repl{{ ReplicatedImageRepository (HelmValue ".Values.image.repository") }}'
    service:
      type: NodePort
      nodePorts:
        http: 80
        https: 443
    deployment:
      imagePullSecrets:
        - name: enterprise-pull-secret
